CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INTEGER,
    PRODUCT_ID VARCHAR(255),
    PRIORITY INTEGER,
    PRICE DOUBLE,
    CURR VARCHAR(10)
);